EXPECTED_TREE = '/\n  src/\n    helper/\n      args_parser.h\n      clipp.h\n      confusion.h\n      cuda_helpers.cuh\n      rngpu.hpp\n    bit_vector_functions.h\n    bit_vector_kernels.cuh\n    config.h\n    cuBool_cpu.h\n    cuBool_gpu.cuh\n    float_kernels.cuh\n    io_and_allocation.hpp\n    main.cu\n    updates_and_measures.cuh\n  CMakeLists.txt\n  LICENSE\n  Makefile\n  README.md'

EXPECTED_MAIN_FILES = ['src/main.cu']

EXPECTED_INCLUDE_TREES = {'src/main.cu': 'src/main.cu\n'
                '  #include <vector> (DNE)\n'
                '  #include <iostream> (DNE)\n'
                '  #include <string> (DNE)\n'
                '  #include "helper/clipp.h"\n'
                '    #include <cstring> (DNE)\n'
                '    #include <string> (DNE)\n'
                '    #include <cstdlib> (DNE)\n'
                '    #include <cstring> (DNE)\n'
                '    #include <cctype> (DNE)\n'
                '    #include <memory> (DNE)\n'
                '    #include <vector> (DNE)\n'
                '    #include <limits> (DNE)\n'
                '    #include <stack> (DNE)\n'
                '    #include <algorithm> (DNE)\n'
                '    #include <sstream> (DNE)\n'
                '    #include <utility> (DNE)\n'
                '    #include <iterator> (DNE)\n'
                '    #include <functional> (DNE)\n'
                '  #include "io_and_allocation.hpp"\n'
                '    #include <iostream> (DNE)\n'
                '    #include <string> (DNE)\n'
                '    #include <sstream> (DNE)\n'
                '    #include <fstream> (DNE)\n'
                '    #include <vector> (DNE)\n'
                '    #include <bitset> (DNE)\n'
                '    #include <ctime> (DNE)\n'
                '    #include <algorithm> (DNE)\n'
                '    #include <numeric> (DNE)\n'
                '    #include <random> (DNE)\n'
                '    #include <cmath> (DNE)\n'
                '    #include <omp.h> (DNE)\n'
                '    #include "config.h"\n'
                '      #include <cstdlib> (DNE)\n'
                '      #include <cstdint> (DNE)\n'
                '      #include <limits> (DNE)\n'
                '    #include "helper/rngpu.hpp"\n'
                '      #include <stdint.h> (DNE)\n'
                '      #include <math.h> (DNE)\n'
                '  #include "bit_vector_functions.h"\n'
                '    #include <vector> (DNE)\n'
                '    #include <bitset> (DNE)\n'
                '    #include "helper/confusion.h"\n'
                '      #include <cstdlib> (DNE)\n'
                '    #include "config.h"\n'
                '      #include <cstdlib> (DNE)\n'
                '      #include <cstdint> (DNE)\n'
                '      #include <limits> (DNE)\n'
                '    #include "io_and_allocation.hpp"\n'
                '      #include <iostream> (DNE)\n'
                '      #include <string> (DNE)\n'
                '      #include <sstream> (DNE)\n'
                '      #include <fstream> (DNE)\n'
                '      #include <vector> (DNE)\n'
                '      #include <bitset> (DNE)\n'
                '      #include <ctime> (DNE)\n'
                '      #include <algorithm> (DNE)\n'
                '      #include <numeric> (DNE)\n'
                '      #include <random> (DNE)\n'
                '      #include <cmath> (DNE)\n'
                '      #include <omp.h> (DNE)\n'
                '      #include "config.h"\n'
                '        #include <cstdlib> (DNE)\n'
                '        #include <cstdint> (DNE)\n'
                '        #include <limits> (DNE)\n'
                '      #include "helper/rngpu.hpp"\n'
                '        #include <stdint.h> (DNE)\n'
                '        #include <math.h> (DNE)\n'
                '    #include "updates_and_measures.cuh"\n'
                '      #include "helper/cuda_helpers.cuh"\n'
                '        #include <iostream> (DNE)\n'
                '        #include <cstdint> (DNE)\n'
                '        #include "../config.h"\n'
                '          #include <cstdlib> (DNE)\n'
                '          #include <cstdint> (DNE)\n'
                '          #include <limits> (DNE)\n'
                '        #include <chrono> (DNE)\n'
                '      #include "helper/rngpu.hpp"\n'
                '        #include <stdint.h> (DNE)\n'
                '        #include <math.h> (DNE)\n'
                '  #include "cuBool_gpu.cuh"\n'
                '    #include <vector> (DNE)\n'
                '    #include <iostream> (DNE)\n'
                '    #include <sstream> (DNE)\n'
                '    #include <limits> (DNE)\n'
                '    #include <type_traits> (DNE)\n'
                '    #include <omp.h> (DNE)\n'
                '    #include "helper/rngpu.hpp"\n'
                '      #include <stdint.h> (DNE)\n'
                '      #include <math.h> (DNE)\n'
                '    #include "helper/cuda_helpers.cuh"\n'
                '      #include <iostream> (DNE)\n'
                '      #include <cstdint> (DNE)\n'
                '      #include "../config.h"\n'
                '        #include <cstdlib> (DNE)\n'
                '        #include <cstdint> (DNE)\n'
                '        #include <limits> (DNE)\n'
                '      #include <chrono> (DNE)\n'
                '    #include "config.h"\n'
                '      #include <cstdlib> (DNE)\n'
                '      #include <cstdint> (DNE)\n'
                '      #include <limits> (DNE)\n'
                '    #include "io_and_allocation.hpp"\n'
                '      #include <iostream> (DNE)\n'
                '      #include <string> (DNE)\n'
                '      #include <sstream> (DNE)\n'
                '      #include <fstream> (DNE)\n'
                '      #include <vector> (DNE)\n'
                '      #include <bitset> (DNE)\n'
                '      #include <ctime> (DNE)\n'
                '      #include <algorithm> (DNE)\n'
                '      #include <numeric> (DNE)\n'
                '      #include <random> (DNE)\n'
                '      #include <cmath> (DNE)\n'
                '      #include <omp.h> (DNE)\n'
                '      #include "config.h"\n'
                '        #include <cstdlib> (DNE)\n'
                '        #include <cstdint> (DNE)\n'
                '        #include <limits> (DNE)\n'
                '      #include "helper/rngpu.hpp"\n'
                '        #include <stdint.h> (DNE)\n'
                '        #include <math.h> (DNE)\n'
                '    #include "bit_vector_kernels.cuh"\n'
                '  #include "cuBool_cpu.h"\n'
                '    #include <vector> (DNE)\n'
                '    #include <iostream> (DNE)\n'
                '    #include <limits> (DNE)\n'
                '    #include <cmath> (DNE)\n'
                '    #include <omp.h> (DNE)\n'
                '    #include "helper/rngpu.hpp"\n'
                '      #include <stdint.h> (DNE)\n'
                '      #include <math.h> (DNE)\n'
                '    #include "helper/confusion.h"\n'
                '      #include <cstdlib> (DNE)\n'
                '    #include "config.h"\n'
                '      #include <cstdlib> (DNE)\n'
                '      #include <cstdint> (DNE)\n'
                '      #include <limits> (DNE)\n'
                '    #include "io_and_allocation.hpp"\n'
                '      #include <iostream> (DNE)\n'
                '      #include <string> (DNE)\n'
                '      #include <sstream> (DNE)\n'
                '      #include <fstream> (DNE)\n'
                '      #include <vector> (DNE)\n'
                '      #include <bitset> (DNE)\n'
                '      #include <ctime> (DNE)\n'
                '      #include <algorithm> (DNE)\n'
                '      #include <numeric> (DNE)\n'
                '      #include <random> (DNE)\n'
                '      #include <cmath> (DNE)\n'
                '      #include <omp.h> (DNE)\n'
                '      #include "config.h"\n'
                '        #include <cstdlib> (DNE)\n'
                '        #include <cstdint> (DNE)\n'
                '        #include <limits> (DNE)\n'
                '      #include "helper/rngpu.hpp"\n'
                '        #include <stdint.h> (DNE)\n'
                '        #include <math.h> (DNE)\n'
                '    #include "bit_vector_functions.h"\n'
                '      #include <vector> (DNE)\n'
                '      #include <bitset> (DNE)\n'
                '      #include "helper/confusion.h"\n'
                '        #include <cstdlib> (DNE)\n'
                '      #include "config.h"\n'
                '        #include <cstdlib> (DNE)\n'
                '        #include <cstdint> (DNE)\n'
                '        #include <limits> (DNE)\n'
                '      #include "io_and_allocation.hpp"\n'
                '        #include <iostream> (DNE)\n'
                '        #include <string> (DNE)\n'
                '        #include <sstream> (DNE)\n'
                '        #include <fstream> (DNE)\n'
                '        #include <vector> (DNE)\n'
                '        #include <bitset> (DNE)\n'
                '        #include <ctime> (DNE)\n'
                '        #include <algorithm> (DNE)\n'
                '        #include <numeric> (DNE)\n'
                '        #include <random> (DNE)\n'
                '        #include <cmath> (DNE)\n'
                '        #include <omp.h> (DNE)\n'
                '        #include "config.h"\n'
                '          #include <cstdlib> (DNE)\n'
                '          #include <cstdint> (DNE)\n'
                '          #include <limits> (DNE)\n'
                '        #include "helper/rngpu.hpp"\n'
                '          #include <stdint.h> (DNE)\n'
                '          #include <math.h> (DNE)\n'
                '      #include "updates_and_measures.cuh"\n'
                '        #include "helper/cuda_helpers.cuh"\n'
                '          #include <iostream> (DNE)\n'
                '          #include <cstdint> (DNE)\n'
                '          #include "../config.h"\n'
                '            #include <cstdlib> (DNE)\n'
                '            #include <cstdint> (DNE)\n'
                '            #include <limits> (DNE)\n'
                '          #include <chrono> (DNE)\n'
                '        #include "helper/rngpu.hpp"\n'
                '          #include <stdint.h> (DNE)\n'
                '          #include <math.h> (DNE)'}

EXPECTED_KERNELS = [{'file': 'src/bit_vector_kernels.cuh',
  'kernel': 'initFactor',
  'line': 31,
  'lines': 25,
  'offset': 30},
 {'file': 'src/bit_vector_kernels.cuh',
  'kernel': 'computeDistanceRows',
  'line': 59,
  'lines': 37,
  'offset': 58},
 {'file': 'src/bit_vector_kernels.cuh',
  'kernel': 'computeDistanceRowsShared',
  'line': 97,
  'lines': 57,
  'offset': 96},
 {'file': 'src/bit_vector_kernels.cuh',
  'kernel': 'vectorMatrixMultCompareRowWarpShared',
  'line': 158,
  'lines': 76,
  'offset': 157},
 {'file': 'src/bit_vector_kernels.cuh',
  'kernel': 'vectorMatrixMultCompareColWarpShared',
  'line': 236,
  'lines': 78,
  'offset': 235},
 {'file': 'src/float_kernels.cuh',
  'kernel': 'initFactor',
  'line': 5,
  'lines': 20,
  'offset': 5},
 {'file': 'src/float_kernels.cuh',
  'kernel': 'computeDistanceRowsShared',
  'line': 28,
  'lines': 69,
  'offset': 28}]
