EXPECTED_TREE = (
    "/\n"
    "  data/\n"
    "    cifar10_faissed/\n"
    "      distances\n"
    "      indices\n"
    "    mnist_faissed/\n"
    "      distances\n"
    "      indices\n"
    "  apply_forces.cu\n"
    "  apply_forces.h\n"
    "  attr_forces.cu\n"
    "  attr_forces.h\n"
    "  common.h\n"
    "  cuda_utils.cu\n"
    "  cuda_utils.h\n"
    "  cxxopts.hpp\n"
    "  debug_utils.cu\n"
    "  debug_utils.h\n"
    "  distance_utils.cu\n"
    "  distance_utils.h\n"
    "  fit_tsne.cu\n"
    "  fit_tsne.h\n"
    "  main.cu\n"
    "  Makefile\n"
    "  math_utils.cu\n"
    "  math_utils.h\n"
    "  matrix_broadcast_utils.cu\n"
    "  matrix_broadcast_utils.h\n"
    "  nbodyfft.cu\n"
    "  nbodyfft.h\n"
    "  options.h\n"
    "  perplexity_search.cu\n"
    "  perplexity_search.h\n"
    "  rep_forces.cu\n"
    "  rep_forces.h\n"
    "  thrust_transform_functions.h"
)

EXPECTED_MAIN_FILES = ["main.cu"]

EXPECTED_INCLUDE_TREES = {
    "main.cu": """main.cu
  #include <time.h> (DNE)
  #include <string> (DNE)
  #include "fit_tsne.h"
    #include "common.h"
      #include <cuda_runtime.h> (DNE)
      #include <thrust/host_vector.h> (DNE)
      #include <thrust/device_vector.h> (DNE)
      #include <thrust/generate.h> (DNE)
      #include <thrust/reduce.h> (DNE)
      #include <thrust/functional.h> (DNE)
      #include <thrust/random.h> (DNE)
      #include <thrust/sequence.h> (DNE)
      #include <thrust/transform.h> (DNE)
      #include <thrust/transform_reduce.h> (DNE)
      #include <thrust/iterator/counting_iterator.h> (DNE)
      #include <thrust/iterator/transform_iterator.h> (DNE)
      #include <thrust/iterator/permutation_iterator.h> (DNE)
      #include <thrust/iterator/constant_iterator.h> (DNE)
      #include <thrust/functional.h> (DNE)
      #include <thrust/fill.h> (DNE)
      #include <thrust/gather.h> (DNE)
      #include <thrust/sort.h> (DNE)
      #include <stdlib.h> (DNE)
      #include <stdio.h> (DNE)
      #include <assert.h> (DNE)
      #include <float.h> (DNE)
      #include <string.h> (DNE)
      #include <math.h> (DNE)
      #include <time.h> (DNE)
      #include <sys/time.h> (DNE)
      #include <random> (DNE)
      #include <stdexcept> (DNE)
      #include <iostream> (DNE)
      #include <fstream> (DNE)
      #include <vector> (DNE)
      #include <numeric> (DNE)
      #include <algorithm> (DNE)
      #include <iomanip> (DNE)
      #include <cmath> (DNE)
    #include "options.h"
      #include <random> (DNE)
      #include <time.h> (DNE)
      #include <iostream> (DNE)
      #include "cuda_utils.h"
        #include "common.h"
          #include <cuda_runtime.h> (DNE)
          #include <thrust/host_vector.h> (DNE)
          #include <thrust/device_vector.h> (DNE)
          #include <thrust/generate.h> (DNE)
          #include <thrust/reduce.h> (DNE)
          #include <thrust/functional.h> (DNE)
          #include <thrust/random.h> (DNE)
          #include <thrust/sequence.h> (DNE)
          #include <thrust/transform.h> (DNE)
          #include <thrust/transform_reduce.h> (DNE)
          #include <thrust/iterator/counting_iterator.h> (DNE)
          #include <thrust/iterator/transform_iterator.h> (DNE)
          #include <thrust/iterator/permutation_iterator.h> (DNE)
          #include <thrust/iterator/constant_iterator.h> (DNE)
          #include <thrust/functional.h> (DNE)
          #include <thrust/fill.h> (DNE)
          #include <thrust/gather.h> (DNE)
          #include <thrust/sort.h> (DNE)
          #include <stdlib.h> (DNE)
          #include <stdio.h> (DNE)
          #include <assert.h> (DNE)
          #include <float.h> (DNE)
          #include <string.h> (DNE)
          #include <math.h> (DNE)
          #include <time.h> (DNE)
          #include <sys/time.h> (DNE)
          #include <random> (DNE)
          #include <stdexcept> (DNE)
          #include <iostream> (DNE)
          #include <fstream> (DNE)
          #include <vector> (DNE)
          #include <numeric> (DNE)
          #include <algorithm> (DNE)
          #include <iomanip> (DNE)
          #include <cmath> (DNE)
    #include "cuda_utils.h"
      #include "common.h"
        #include <cuda_runtime.h> (DNE)
        #include <thrust/host_vector.h> (DNE)
        #include <thrust/device_vector.h> (DNE)
        #include <thrust/generate.h> (DNE)
        #include <thrust/reduce.h> (DNE)
        #include <thrust/functional.h> (DNE)
        #include <thrust/random.h> (DNE)
        #include <thrust/sequence.h> (DNE)
        #include <thrust/transform.h> (DNE)
        #include <thrust/transform_reduce.h> (DNE)
        #include <thrust/iterator/counting_iterator.h> (DNE)
        #include <thrust/iterator/transform_iterator.h> (DNE)
        #include <thrust/iterator/permutation_iterator.h> (DNE)
        #include <thrust/iterator/constant_iterator.h> (DNE)
        #include <thrust/functional.h> (DNE)
        #include <thrust/fill.h> (DNE)
        #include <thrust/gather.h> (DNE)
        #include <thrust/sort.h> (DNE)
        #include <stdlib.h> (DNE)
        #include <stdio.h> (DNE)
        #include <assert.h> (DNE)
        #include <float.h> (DNE)
        #include <string.h> (DNE)
        #include <math.h> (DNE)
        #include <time.h> (DNE)
        #include <sys/time.h> (DNE)
        #include <random> (DNE)
        #include <stdexcept> (DNE)
        #include <iostream> (DNE)
        #include <fstream> (DNE)
        #include <vector> (DNE)
        #include <numeric> (DNE)
        #include <algorithm> (DNE)
        #include <iomanip> (DNE)
        #include <cmath> (DNE)
    #include "debug_utils.h"
      #include "common.h"
        #include <cuda_runtime.h> (DNE)
        #include <thrust/host_vector.h> (DNE)
        #include <thrust/device_vector.h> (DNE)
        #include <thrust/generate.h> (DNE)
        #include <thrust/reduce.h> (DNE)
        #include <thrust/functional.h> (DNE)
        #include <thrust/random.h> (DNE)
        #include <thrust/sequence.h> (DNE)
        #include <thrust/transform.h> (DNE)
        #include <thrust/transform_reduce.h> (DNE)
        #include <thrust/iterator/counting_iterator.h> (DNE)
        #include <thrust/iterator/transform_iterator.h> (DNE)
        #include <thrust/iterator/permutation_iterator.h> (DNE)
        #include <thrust/iterator/constant_iterator.h> (DNE)
        #include <thrust/functional.h> (DNE)
        #include <thrust/fill.h> (DNE)
        #include <thrust/gather.h> (DNE)
        #include <thrust/sort.h> (DNE)
        #include <stdlib.h> (DNE)
        #include <stdio.h> (DNE)
        #include <assert.h> (DNE)
        #include <float.h> (DNE)
        #include <string.h> (DNE)
        #include <math.h> (DNE)
        #include <time.h> (DNE)
        #include <sys/time.h> (DNE)
        #include <random> (DNE)
        #include <stdexcept> (DNE)
        #include <iostream> (DNE)
        #include <fstream> (DNE)
        #include <vector> (DNE)
        #include <numeric> (DNE)
        #include <algorithm> (DNE)
        #include <iomanip> (DNE)
        #include <cmath> (DNE)
    #include "math_utils.h"
      #include "common.h"
        #include <cuda_runtime.h> (DNE)
        #include <thrust/host_vector.h> (DNE)
        #include <thrust/device_vector.h> (DNE)
        #include <thrust/generate.h> (DNE)
        #include <thrust/reduce.h> (DNE)
        #include <thrust/functional.h> (DNE)
        #include <thrust/random.h> (DNE)
        #include <thrust/sequence.h> (DNE)
        #include <thrust/transform.h> (DNE)
        #include <thrust/transform_reduce.h> (DNE)
        #include <thrust/iterator/counting_iterator.h> (DNE)
        #include <thrust/iterator/transform_iterator.h> (DNE)
        #include <thrust/iterator/permutation_iterator.h> (DNE)
        #include <thrust/iterator/constant_iterator.h> (DNE)
        #include <thrust/functional.h> (DNE)
        #include <thrust/fill.h> (DNE)
        #include <thrust/gather.h> (DNE)
        #include <thrust/sort.h> (DNE)
        #include <stdlib.h> (DNE)
        #include <stdio.h> (DNE)
        #include <assert.h> (DNE)
        #include <float.h> (DNE)
        #include <string.h> (DNE)
        #include <math.h> (DNE)
        #include <time.h> (DNE)
        #include <sys/time.h> (DNE)
        #include <random> (DNE)
        #include <stdexcept> (DNE)
        #include <iostream> (DNE)
        #include <fstream> (DNE)
        #include <vector> (DNE)
        #include <numeric> (DNE)
        #include <algorithm> (DNE)
        #include <iomanip> (DNE)
        #include <cmath> (DNE)
      #include "options.h"
        #include <random> (DNE)
        #include <time.h> (DNE)
        #include <iostream> (DNE)
        #include "cuda_utils.h"
          #include "common.h"
            #include <cuda_runtime.h> (DNE)
            #include <thrust/host_vector.h> (DNE)
            #include <thrust/device_vector.h> (DNE)
            #include <thrust/generate.h> (DNE)
            #include <thrust/reduce.h> (DNE)
            #include <thrust/functional.h> (DNE)
            #include <thrust/random.h> (DNE)
            #include <thrust/sequence.h> (DNE)
            #include <thrust/transform.h> (DNE)
            #include <thrust/transform_reduce.h> (DNE)
            #include <thrust/iterator/counting_iterator.h> (DNE)
            #include <thrust/iterator/transform_iterator.h> (DNE)
            #include <thrust/iterator/permutation_iterator.h> (DNE)
            #include <thrust/iterator/constant_iterator.h> (DNE)
            #include <thrust/functional.h> (DNE)
            #include <thrust/fill.h> (DNE)
            #include <thrust/gather.h> (DNE)
            #include <thrust/sort.h> (DNE)
            #include <stdlib.h> (DNE)
            #include <stdio.h> (DNE)
            #include <assert.h> (DNE)
            #include <float.h> (DNE)
            #include <string.h> (DNE)
            #include <math.h> (DNE)
            #include <time.h> (DNE)
            #include <sys/time.h> (DNE)
            #include <random> (DNE)
            #include <stdexcept> (DNE)
            #include <iostream> (DNE)
            #include <fstream> (DNE)
            #include <vector> (DNE)
            #include <numeric> (DNE)
            #include <algorithm> (DNE)
            #include <iomanip> (DNE)
            #include <cmath> (DNE)
      #include "matrix_broadcast_utils.h"
        #include "common.h"
          #include <cuda_runtime.h> (DNE)
          #include <thrust/host_vector.h> (DNE)
          #include <thrust/device_vector.h> (DNE)
          #include <thrust/generate.h> (DNE)
          #include <thrust/reduce.h> (DNE)
          #include <thrust/functional.h> (DNE)
          #include <thrust/random.h> (DNE)
          #include <thrust/sequence.h> (DNE)
          #include <thrust/transform.h> (DNE)
          #include <thrust/transform_reduce.h> (DNE)
          #include <thrust/iterator/counting_iterator.h> (DNE)
          #include <thrust/iterator/transform_iterator.h> (DNE)
          #include <thrust/iterator/permutation_iterator.h> (DNE)
          #include <thrust/iterator/constant_iterator.h> (DNE)
          #include <thrust/functional.h> (DNE)
          #include <thrust/fill.h> (DNE)
          #include <thrust/gather.h> (DNE)
          #include <thrust/sort.h> (DNE)
          #include <stdlib.h> (DNE)
          #include <stdio.h> (DNE)
          #include <assert.h> (DNE)
          #include <float.h> (DNE)
          #include <string.h> (DNE)
          #include <math.h> (DNE)
          #include <time.h> (DNE)
          #include <sys/time.h> (DNE)
          #include <random> (DNE)
          #include <stdexcept> (DNE)
          #include <iostream> (DNE)
          #include <fstream> (DNE)
          #include <vector> (DNE)
          #include <numeric> (DNE)
          #include <algorithm> (DNE)
          #include <iomanip> (DNE)
          #include <cmath> (DNE)
        #include "cuda_utils.h"
          #include "common.h"
            #include <cuda_runtime.h> (DNE)
            #include <thrust/host_vector.h> (DNE)
            #include <thrust/device_vector.h> (DNE)
            #include <thrust/generate.h> (DNE)
            #include <thrust/reduce.h> (DNE)
            #include <thrust/functional.h> (DNE)
            #include <thrust/random.h> (DNE)
            #include <thrust/sequence.h> (DNE)
            #include <thrust/transform.h> (DNE)
            #include <thrust/transform_reduce.h> (DNE)
            #include <thrust/iterator/counting_iterator.h> (DNE)
            #include <thrust/iterator/transform_iterator.h> (DNE)
            #include <thrust/iterator/permutation_iterator.h> (DNE)
            #include <thrust/iterator/constant_iterator.h> (DNE)
            #include <thrust/functional.h> (DNE)
            #include <thrust/fill.h> (DNE)
            #include <thrust/gather.h> (DNE)
            #include <thrust/sort.h> (DNE)
            #include <stdlib.h> (DNE)
            #include <stdio.h> (DNE)
            #include <assert.h> (DNE)
            #include <float.h> (DNE)
            #include <string.h> (DNE)
            #include <math.h> (DNE)
            #include <time.h> (DNE)
            #include <sys/time.h> (DNE)
            #include <random> (DNE)
            #include <stdexcept> (DNE)
            #include <iostream> (DNE)
            #include <fstream> (DNE)
            #include <vector> (DNE)
            #include <numeric> (DNE)
            #include <algorithm> (DNE)
            #include <iomanip> (DNE)
            #include <cmath> (DNE)
      #include "thrust_transform_functions.h"
    #include "matrix_broadcast_utils.h"
      #include "common.h"
        #include <cuda_runtime.h> (DNE)
        #include <thrust/host_vector.h> (DNE)
        #include <thrust/device_vector.h> (DNE)
        #include <thrust/generate.h> (DNE)
        #include <thrust/reduce.h> (DNE)
        #include <thrust/functional.h> (DNE)
        #include <thrust/random.h> (DNE)
        #include <thrust/sequence.h> (DNE)
        #include <thrust/transform.h> (DNE)
        #include <thrust/transform_reduce.h> (DNE)
        #include <thrust/iterator/counting_iterator.h> (DNE)
        #include <thrust/iterator/transform_iterator.h> (DNE)
        #include <thrust/iterator/permutation_iterator.h> (DNE)
        #include <thrust/iterator/constant_iterator.h> (DNE)
        #include <thrust/functional.h> (DNE)
        #include <thrust/fill.h> (DNE)
        #include <thrust/gather.h> (DNE)
        #include <thrust/sort.h> (DNE)
        #include <stdlib.h> (DNE)
        #include <stdio.h> (DNE)
        #include <assert.h> (DNE)
        #include <float.h> (DNE)
        #include <string.h> (DNE)
        #include <math.h> (DNE)
        #include <time.h> (DNE)
        #include <sys/time.h> (DNE)
        #include <random> (DNE)
        #include <stdexcept> (DNE)
        #include <iostream> (DNE)
        #include <fstream> (DNE)
        #include <vector> (DNE)
        #include <numeric> (DNE)
        #include <algorithm> (DNE)
        #include <iomanip> (DNE)
        #include <cmath> (DNE)
      #include "cuda_utils.h"
        #include "common.h"
          #include <cuda_runtime.h> (DNE)
          #include <thrust/host_vector.h> (DNE)
          #include <thrust/device_vector.h> (DNE)
          #include <thrust/generate.h> (DNE)
          #include <thrust/reduce.h> (DNE)
          #include <thrust/functional.h> (DNE)
          #include <thrust/random.h> (DNE)
          #include <thrust/sequence.h> (DNE)
          #include <thrust/transform.h> (DNE)
          #include <thrust/transform_reduce.h> (DNE)
          #include <thrust/iterator/counting_iterator.h> (DNE)
          #include <thrust/iterator/transform_iterator.h> (DNE)
          #include <thrust/iterator/permutation_iterator.h> (DNE)
          #include <thrust/iterator/constant_iterator.h> (DNE)
          #include <thrust/functional.h> (DNE)
          #include <thrust/fill.h> (DNE)
          #include <thrust/gather.h> (DNE)
          #include <thrust/sort.h> (DNE)
          #include <stdlib.h> (DNE)
          #include <stdio.h> (DNE)
          #include <assert.h> (DNE)
          #include <float.h> (DNE)
          #include <string.h> (DNE)
          #include <math.h> (DNE)
          #include <time.h> (DNE)
          #include <sys/time.h> (DNE)
          #include <random> (DNE)
          #include <stdexcept> (DNE)
          #include <iostream> (DNE)
          #include <fstream> (DNE)
          #include <vector> (DNE)
          #include <numeric> (DNE)
          #include <algorithm> (DNE)
          #include <iomanip> (DNE)
          #include <cmath> (DNE)
    #include "distance_utils.h"
      #include <stdint.h> (DNE)
      #include "common.h"
        #include <cuda_runtime.h> (DNE)
        #include <thrust/host_vector.h> (DNE)
        #include <thrust/device_vector.h> (DNE)
        #include <thrust/generate.h> (DNE)
        #include <thrust/reduce.h> (DNE)
        #include <thrust/functional.h> (DNE)
        #include <thrust/random.h> (DNE)
        #include <thrust/sequence.h> (DNE)
        #include <thrust/transform.h> (DNE)
        #include <thrust/transform_reduce.h> (DNE)
        #include <thrust/iterator/counting_iterator.h> (DNE)
        #include <thrust/iterator/transform_iterator.h> (DNE)
        #include <thrust/iterator/permutation_iterator.h> (DNE)
        #include <thrust/iterator/constant_iterator.h> (DNE)
        #include <thrust/functional.h> (DNE)
        #include <thrust/fill.h> (DNE)
        #include <thrust/gather.h> (DNE)
        #include <thrust/sort.h> (DNE)
        #include <stdlib.h> (DNE)
        #include <stdio.h> (DNE)
        #include <assert.h> (DNE)
        #include <float.h> (DNE)
        #include <string.h> (DNE)
        #include <math.h> (DNE)
        #include <time.h> (DNE)
        #include <sys/time.h> (DNE)
        #include <random> (DNE)
        #include <stdexcept> (DNE)
        #include <iostream> (DNE)
        #include <fstream> (DNE)
        #include <vector> (DNE)
        #include <numeric> (DNE)
        #include <algorithm> (DNE)
        #include <iomanip> (DNE)
        #include <cmath> (DNE)
      #include "options.h"
        #include <random> (DNE)
        #include <time.h> (DNE)
        #include <iostream> (DNE)
        #include "cuda_utils.h"
          #include "common.h"
            #include <cuda_runtime.h> (DNE)
            #include <thrust/host_vector.h> (DNE)
            #include <thrust/device_vector.h> (DNE)
            #include <thrust/generate.h> (DNE)
            #include <thrust/reduce.h> (DNE)
            #include <thrust/functional.h> (DNE)
            #include <thrust/random.h> (DNE)
            #include <thrust/sequence.h> (DNE)
            #include <thrust/transform.h> (DNE)
            #include <thrust/transform_reduce.h> (DNE)
            #include <thrust/iterator/counting_iterator.h> (DNE)
            #include <thrust/iterator/transform_iterator.h> (DNE)
            #include <thrust/iterator/permutation_iterator.h> (DNE)
            #include <thrust/iterator/constant_iterator.h> (DNE)
            #include <thrust/functional.h> (DNE)
            #include <thrust/fill.h> (DNE)
            #include <thrust/gather.h> (DNE)
            #include <thrust/sort.h> (DNE)
            #include <stdlib.h> (DNE)
            #include <stdio.h> (DNE)
            #include <assert.h> (DNE)
            #include <float.h> (DNE)
            #include <string.h> (DNE)
            #include <math.h> (DNE)
            #include <time.h> (DNE)
            #include <sys/time.h> (DNE)
            #include <random> (DNE)
            #include <stdexcept> (DNE)
            #include <iostream> (DNE)
            #include <fstream> (DNE)
            #include <vector> (DNE)
            #include <numeric> (DNE)
            #include <algorithm> (DNE)
            #include <iomanip> (DNE)
            #include <cmath> (DNE)
      #include "cuda_utils.h"
        #include "common.h"
          #include <cuda_runtime.h> (DNE)
          #include <thrust/host_vector.h> (DNE)
          #include <thrust/device_vector.h> (DNE)
          #include <thrust/generate.h> (DNE)
          #include <thrust/reduce.h> (DNE)
          #include <thrust/functional.h> (DNE)
          #include <thrust/random.h> (DNE)
          #include <thrust/sequence.h> (DNE)
          #include <thrust/transform.h> (DNE)
          #include <thrust/transform_reduce.h> (DNE)
          #include <thrust/iterator/counting_iterator.h> (DNE)
          #include <thrust/iterator/transform_iterator.h> (DNE)
          #include <thrust/iterator/permutation_iterator.h> (DNE)
          #include <thrust/iterator/constant_iterator.h> (DNE)
          #include <thrust/functional.h> (DNE)
          #include <thrust/fill.h> (DNE)
          #include <thrust/gather.h> (DNE)
          #include <thrust/sort.h> (DNE)
          #include <stdlib.h> (DNE)
          #include <stdio.h> (DNE)
          #include <assert.h> (DNE)
          #include <float.h> (DNE)
          #include <string.h> (DNE)
          #include <math.h> (DNE)
          #include <time.h> (DNE)
          #include <sys/time.h> (DNE)
          #include <random> (DNE)
          #include <stdexcept> (DNE)
          #include <iostream> (DNE)
          #include <fstream> (DNE)
          #include <vector> (DNE)
          #include <numeric> (DNE)
          #include <algorithm> (DNE)
          #include <iomanip> (DNE)
          #include <cmath> (DNE)
      #include "math_utils.h"
        #include "common.h"
          #include <cuda_runtime.h> (DNE)
          #include <thrust/host_vector.h> (DNE)
          #include <thrust/device_vector.h> (DNE)
          #include <thrust/generate.h> (DNE)
          #include <thrust/reduce.h> (DNE)
          #include <thrust/functional.h> (DNE)
          #include <thrust/random.h> (DNE)
          #include <thrust/sequence.h> (DNE)
          #include <thrust/transform.h> (DNE)
          #include <thrust/transform_reduce.h> (DNE)
          #include <thrust/iterator/counting_iterator.h> (DNE)
          #include <thrust/iterator/transform_iterator.h> (DNE)
          #include <thrust/iterator/permutation_iterator.h> (DNE)
          #include <thrust/iterator/constant_iterator.h> (DNE)
          #include <thrust/functional.h> (DNE)
          #include <thrust/fill.h> (DNE)
          #include <thrust/gather.h> (DNE)
          #include <thrust/sort.h> (DNE)
          #include <stdlib.h> (DNE)
          #include <stdio.h> (DNE)
          #include <assert.h> (DNE)
          #include <float.h> (DNE)
          #include <string.h> (DNE)
          #include <math.h> (DNE)
          #include <time.h> (DNE)
          #include <sys/time.h> (DNE)
          #include <random> (DNE)
          #include <stdexcept> (DNE)
          #include <iostream> (DNE)
          #include <fstream> (DNE)
          #include <vector> (DNE)
          #include <numeric> (DNE)
          #include <algorithm> (DNE)
          #include <iomanip> (DNE)
          #include <cmath> (DNE)
        #include "options.h"
          #include <random> (DNE)
          #include <time.h> (DNE)
          #include <iostream> (DNE)
          #include "cuda_utils.h"
            #include "common.h"
              #include <cuda_runtime.h> (DNE)
              #include <thrust/host_vector.h> (DNE)
              #include <thrust/device_vector.h> (DNE)
              #include <thrust/generate.h> (DNE)
              #include <thrust/reduce.h> (DNE)
              #include <thrust/functional.h> (DNE)
              #include <thrust/random.h> (DNE)
              #include <thrust/sequence.h> (DNE)
              #include <thrust/transform.h> (DNE)
              #include <thrust/transform_reduce.h> (DNE)
              #include <thrust/iterator/counting_iterator.h> (DNE)
              #include <thrust/iterator/transform_iterator.h> (DNE)
              #include <thrust/iterator/permutation_iterator.h> (DNE)
              #include <thrust/iterator/constant_iterator.h> (DNE)
              #include <thrust/functional.h> (DNE)
              #include <thrust/fill.h> (DNE)
              #include <thrust/gather.h> (DNE)
              #include <thrust/sort.h> (DNE)
              #include <stdlib.h> (DNE)
              #include <stdio.h> (DNE)
              #include <assert.h> (DNE)
              #include <float.h> (DNE)
              #include <string.h> (DNE)
              #include <math.h> (DNE)
              #include <time.h> (DNE)
              #include <sys/time.h> (DNE)
              #include <random> (DNE)
              #include <stdexcept> (DNE)
              #include <iostream> (DNE)
              #include <fstream> (DNE)
              #include <vector> (DNE)
              #include <numeric> (DNE)
              #include <algorithm> (DNE)
              #include <iomanip> (DNE)
              #include <cmath> (DNE)
        #include "matrix_broadcast_utils.h"
          #include "common.h"
            #include <cuda_runtime.h> (DNE)
            #include <thrust/host_vector.h> (DNE)
            #include <thrust/device_vector.h> (DNE)
            #include <thrust/generate.h> (DNE)
            #include <thrust/reduce.h> (DNE)
            #include <thrust/functional.h> (DNE)
            #include <thrust/random.h> (DNE)
            #include <thrust/sequence.h> (DNE)
            #include <thrust/transform.h> (DNE)
            #include <thrust/transform_reduce.h> (DNE)
            #include <thrust/iterator/counting_iterator.h> (DNE)
            #include <thrust/iterator/transform_iterator.h> (DNE)
            #include <thrust/iterator/permutation_iterator.h> (DNE)
            #include <thrust/iterator/constant_iterator.h> (DNE)
            #include <thrust/functional.h> (DNE)
            #include <thrust/fill.h> (DNE)
            #include <thrust/gather.h> (DNE)
            #include <thrust/sort.h> (DNE)
            #include <stdlib.h> (DNE)
            #include <stdio.h> (DNE)
            #include <assert.h> (DNE)
            #include <float.h> (DNE)
            #include <string.h> (DNE)
            #include <math.h> (DNE)
            #include <time.h> (DNE)
            #include <sys/time.h> (DNE)
            #include <random> (DNE)
            #include <stdexcept> (DNE)
            #include <iostream> (DNE)
            #include <fstream> (DNE)
            #include <vector> (DNE)
            #include <numeric> (DNE)
            #include <algorithm> (DNE)
            #include <iomanip> (DNE)
            #include <cmath> (DNE)
          #include "cuda_utils.h"
            #include "common.h"
              #include <cuda_runtime.h> (DNE)
              #include <thrust/host_vector.h> (DNE)
              #include <thrust/device_vector.h> (DNE)
              #include <thrust/generate.h> (DNE)
              #include <thrust/reduce.h> (DNE)
              #include <thrust/functional.h> (DNE)
              #include <thrust/random.h> (DNE)
              #include <thrust/sequence.h> (DNE)
              #include <thrust/transform.h> (DNE)
              #include <thrust/transform_reduce.h> (DNE)
              #include <thrust/iterator/counting_iterator.h> (DNE)
              #include <thrust/iterator/transform_iterator.h> (DNE)
              #include <thrust/iterator/permutation_iterator.h> (DNE)
              #include <thrust/iterator/constant_iterator.h> (DNE)
              #include <thrust/functional.h> (DNE)
              #include <thrust/fill.h> (DNE)
              #include <thrust/gather.h> (DNE)
              #include <thrust/sort.h> (DNE)
              #include <stdlib.h> (DNE)
              #include <stdio.h> (DNE)
              #include <assert.h> (DNE)
              #include <float.h> (DNE)
              #include <string.h> (DNE)
              #include <math.h> (DNE)
              #include <time.h> (DNE)
              #include <sys/time.h> (DNE)
              #include <random> (DNE)
              #include <stdexcept> (DNE)
              #include <iostream> (DNE)
              #include <fstream> (DNE)
              #include <vector> (DNE)
              #include <numeric> (DNE)
              #include <algorithm> (DNE)
              #include <iomanip> (DNE)
              #include <cmath> (DNE)
        #include "thrust_transform_functions.h"
    #include "apply_forces.h"
      #include "common.h"
        #include <cuda_runtime.h> (DNE)
        #include <thrust/host_vector.h> (DNE)
        #include <thrust/device_vector.h> (DNE)
        #include <thrust/generate.h> (DNE)
        #include <thrust/reduce.h> (DNE)
        #include <thrust/functional.h> (DNE)
        #include <thrust/random.h> (DNE)
        #include <thrust/sequence.h> (DNE)
        #include <thrust/transform.h> (DNE)
        #include <thrust/transform_reduce.h> (DNE)
        #include <thrust/iterator/counting_iterator.h> (DNE)
        #include <thrust/iterator/transform_iterator.h> (DNE)
        #include <thrust/iterator/permutation_iterator.h> (DNE)
        #include <thrust/iterator/constant_iterator.h> (DNE)
        #include <thrust/functional.h> (DNE)
        #include <thrust/fill.h> (DNE)
        #include <thrust/gather.h> (DNE)
        #include <thrust/sort.h> (DNE)
        #include <stdlib.h> (DNE)
        #include <stdio.h> (DNE)
        #include <assert.h> (DNE)
        #include <float.h> (DNE)
        #include <string.h> (DNE)
        #include <math.h> (DNE)
        #include <time.h> (DNE)
        #include <sys/time.h> (DNE)
        #include <random> (DNE)
        #include <stdexcept> (DNE)
        #include <iostream> (DNE)
        #include <fstream> (DNE)
        #include <vector> (DNE)
        #include <numeric> (DNE)
        #include <algorithm> (DNE)
        #include <iomanip> (DNE)
        #include <cmath> (DNE)
      #include "options.h"
        #include <random> (DNE)
        #include <time.h> (DNE)
        #include <iostream> (DNE)
        #include "cuda_utils.h"
          #include "common.h"
            #include <cuda_runtime.h> (DNE)
            #include <thrust/host_vector.h> (DNE)
            #include <thrust/device_vector.h> (DNE)
            #include <thrust/generate.h> (DNE)
            #include <thrust/reduce.h> (DNE)
            #include <thrust/functional.h> (DNE)
            #include <thrust/random.h> (DNE)
            #include <thrust/sequence.h> (DNE)
            #include <thrust/transform.h> (DNE)
            #include <thrust/transform_reduce.h> (DNE)
            #include <thrust/iterator/counting_iterator.h> (DNE)
            #include <thrust/iterator/transform_iterator.h> (DNE)
            #include <thrust/iterator/permutation_iterator.h> (DNE)
            #include <thrust/iterator/constant_iterator.h> (DNE)
            #include <thrust/functional.h> (DNE)
            #include <thrust/fill.h> (DNE)
            #include <thrust/gather.h> (DNE)
            #include <thrust/sort.h> (DNE)
            #include <stdlib.h> (DNE)
            #include <stdio.h> (DNE)
            #include <assert.h> (DNE)
            #include <float.h> (DNE)
            #include <string.h> (DNE)
            #include <math.h> (DNE)
            #include <time.h> (DNE)
            #include <sys/time.h> (DNE)
            #include <random> (DNE)
            #include <stdexcept> (DNE)
            #include <iostream> (DNE)
            #include <fstream> (DNE)
            #include <vector> (DNE)
            #include <numeric> (DNE)
            #include <algorithm> (DNE)
            #include <iomanip> (DNE)
            #include <cmath> (DNE)
      #include "cuda_utils.h"
        #include "common.h"
          #include <cuda_runtime.h> (DNE)
          #include <thrust/host_vector.h> (DNE)
          #include <thrust/device_vector.h> (DNE)
          #include <thrust/generate.h> (DNE)
          #include <thrust/reduce.h> (DNE)
          #include <thrust/functional.h> (DNE)
          #include <thrust/random.h> (DNE)
          #include <thrust/sequence.h> (DNE)
          #include <thrust/transform.h> (DNE)
          #include <thrust/transform_reduce.h> (DNE)
          #include <thrust/iterator/counting_iterator.h> (DNE)
          #include <thrust/iterator/transform_iterator.h> (DNE)
          #include <thrust/iterator/permutation_iterator.h> (DNE)
          #include <thrust/iterator/constant_iterator.h> (DNE)
          #include <thrust/functional.h> (DNE)
          #include <thrust/fill.h> (DNE)
          #include <thrust/gather.h> (DNE)
          #include <thrust/sort.h> (DNE)
          #include <stdlib.h> (DNE)
          #include <stdio.h> (DNE)
          #include <assert.h> (DNE)
          #include <float.h> (DNE)
          #include <string.h> (DNE)
          #include <math.h> (DNE)
          #include <time.h> (DNE)
          #include <sys/time.h> (DNE)
          #include <random> (DNE)
          #include <stdexcept> (DNE)
          #include <iostream> (DNE)
          #include <fstream> (DNE)
          #include <vector> (DNE)
          #include <numeric> (DNE)
          #include <algorithm> (DNE)
          #include <iomanip> (DNE)
          #include <cmath> (DNE)
    #include "attr_forces.h"
      #include "common.h"
        #include <cuda_runtime.h> (DNE)
        #include <thrust/host_vector.h> (DNE)
        #include <thrust/device_vector.h> (DNE)
        #include <thrust/generate.h> (DNE)
        #include <thrust/reduce.h> (DNE)
        #include <thrust/functional.h> (DNE)
        #include <thrust/random.h> (DNE)
        #include <thrust/sequence.h> (DNE)
        #include <thrust/transform.h> (DNE)
        #include <thrust/transform_reduce.h> (DNE)
        #include <thrust/iterator/counting_iterator.h> (DNE)
        #include <thrust/iterator/transform_iterator.h> (DNE)
        #include <thrust/iterator/permutation_iterator.h> (DNE)
        #include <thrust/iterator/constant_iterator.h> (DNE)
        #include <thrust/functional.h> (DNE)
        #include <thrust/fill.h> (DNE)
        #include <thrust/gather.h> (DNE)
        #include <thrust/sort.h> (DNE)
        #include <stdlib.h> (DNE)
        #include <stdio.h> (DNE)
        #include <assert.h> (DNE)
        #include <float.h> (DNE)
        #include <string.h> (DNE)
        #include <math.h> (DNE)
        #include <time.h> (DNE)
        #include <sys/time.h> (DNE)
        #include <random> (DNE)
        #include <stdexcept> (DNE)
        #include <iostream> (DNE)
        #include <fstream> (DNE)
        #include <vector> (DNE)
        #include <numeric> (DNE)
        #include <algorithm> (DNE)
        #include <iomanip> (DNE)
        #include <cmath> (DNE)
      #include "options.h"
        #include <random> (DNE)
        #include <time.h> (DNE)
        #include <iostream> (DNE)
        #include "cuda_utils.h"
          #include "common.h"
            #include <cuda_runtime.h> (DNE)
            #include <thrust/host_vector.h> (DNE)
            #include <thrust/device_vector.h> (DNE)
            #include <thrust/generate.h> (DNE)
            #include <thrust/reduce.h> (DNE)
            #include <thrust/functional.h> (DNE)
            #include <thrust/random.h> (DNE)
            #include <thrust/sequence.h> (DNE)
            #include <thrust/transform.h> (DNE)
            #include <thrust/transform_reduce.h> (DNE)
            #include <thrust/iterator/counting_iterator.h> (DNE)
            #include <thrust/iterator/transform_iterator.h> (DNE)
            #include <thrust/iterator/permutation_iterator.h> (DNE)
            #include <thrust/iterator/constant_iterator.h> (DNE)
            #include <thrust/functional.h> (DNE)
            #include <thrust/fill.h> (DNE)
            #include <thrust/gather.h> (DNE)
            #include <thrust/sort.h> (DNE)
            #include <stdlib.h> (DNE)
            #include <stdio.h> (DNE)
            #include <assert.h> (DNE)
            #include <float.h> (DNE)
            #include <string.h> (DNE)
            #include <math.h> (DNE)
            #include <time.h> (DNE)
            #include <sys/time.h> (DNE)
            #include <random> (DNE)
            #include <stdexcept> (DNE)
            #include <iostream> (DNE)
            #include <fstream> (DNE)
            #include <vector> (DNE)
            #include <numeric> (DNE)
            #include <algorithm> (DNE)
            #include <iomanip> (DNE)
            #include <cmath> (DNE)
      #include "cuda_utils.h"
        #include "common.h"
          #include <cuda_runtime.h> (DNE)
          #include <thrust/host_vector.h> (DNE)
          #include <thrust/device_vector.h> (DNE)
          #include <thrust/generate.h> (DNE)
          #include <thrust/reduce.h> (DNE)
          #include <thrust/functional.h> (DNE)
          #include <thrust/random.h> (DNE)
          #include <thrust/sequence.h> (DNE)
          #include <thrust/transform.h> (DNE)
          #include <thrust/transform_reduce.h> (DNE)
          #include <thrust/iterator/counting_iterator.h> (DNE)
          #include <thrust/iterator/transform_iterator.h> (DNE)
          #include <thrust/iterator/permutation_iterator.h> (DNE)
          #include <thrust/iterator/constant_iterator.h> (DNE)
          #include <thrust/functional.h> (DNE)
          #include <thrust/fill.h> (DNE)
          #include <thrust/gather.h> (DNE)
          #include <thrust/sort.h> (DNE)
          #include <stdlib.h> (DNE)
          #include <stdio.h> (DNE)
          #include <assert.h> (DNE)
          #include <float.h> (DNE)
          #include <string.h> (DNE)
          #include <math.h> (DNE)
          #include <time.h> (DNE)
          #include <sys/time.h> (DNE)
          #include <random> (DNE)
          #include <stdexcept> (DNE)
          #include <iostream> (DNE)
          #include <fstream> (DNE)
          #include <vector> (DNE)
          #include <numeric> (DNE)
          #include <algorithm> (DNE)
          #include <iomanip> (DNE)
          #include <cmath> (DNE)
      #include "debug_utils.h"
        #include "common.h"
          #include <cuda_runtime.h> (DNE)
          #include <thrust/host_vector.h> (DNE)
          #include <thrust/device_vector.h> (DNE)
          #include <thrust/generate.h> (DNE)
          #include <thrust/reduce.h> (DNE)
          #include <thrust/functional.h> (DNE)
          #include <thrust/random.h> (DNE)
          #include <thrust/sequence.h> (DNE)
          #include <thrust/transform.h> (DNE)
          #include <thrust/transform_reduce.h> (DNE)
          #include <thrust/iterator/counting_iterator.h> (DNE)
          #include <thrust/iterator/transform_iterator.h> (DNE)
          #include <thrust/iterator/permutation_iterator.h> (DNE)
          #include <thrust/iterator/constant_iterator.h> (DNE)
          #include <thrust/functional.h> (DNE)
          #include <thrust/fill.h> (DNE)
          #include <thrust/gather.h> (DNE)
          #include <thrust/sort.h> (DNE)
          #include <stdlib.h> (DNE)
          #include <stdio.h> (DNE)
          #include <assert.h> (DNE)
          #include <float.h> (DNE)
          #include <string.h> (DNE)
          #include <math.h> (DNE)
          #include <time.h> (DNE)
          #include <sys/time.h> (DNE)
          #include <random> (DNE)
          #include <stdexcept> (DNE)
          #include <iostream> (DNE)
          #include <fstream> (DNE)
          #include <vector> (DNE)
          #include <numeric> (DNE)
          #include <algorithm> (DNE)
          #include <iomanip> (DNE)
          #include <cmath> (DNE)
    #include "perplexity_search.h"
      #include "common.h"
        #include <cuda_runtime.h> (DNE)
        #include <thrust/host_vector.h> (DNE)
        #include <thrust/device_vector.h> (DNE)
        #include <thrust/generate.h> (DNE)
        #include <thrust/reduce.h> (DNE)
        #include <thrust/functional.h> (DNE)
        #include <thrust/random.h> (DNE)
        #include <thrust/sequence.h> (DNE)
        #include <thrust/transform.h> (DNE)
        #include <thrust/transform_reduce.h> (DNE)
        #include <thrust/iterator/counting_iterator.h> (DNE)
        #include <thrust/iterator/transform_iterator.h> (DNE)
        #include <thrust/iterator/permutation_iterator.h> (DNE)
        #include <thrust/iterator/constant_iterator.h> (DNE)
        #include <thrust/functional.h> (DNE)
        #include <thrust/fill.h> (DNE)
        #include <thrust/gather.h> (DNE)
        #include <thrust/sort.h> (DNE)
        #include <stdlib.h> (DNE)
        #include <stdio.h> (DNE)
        #include <assert.h> (DNE)
        #include <float.h> (DNE)
        #include <string.h> (DNE)
        #include <math.h> (DNE)
        #include <time.h> (DNE)
        #include <sys/time.h> (DNE)
        #include <random> (DNE)
        #include <stdexcept> (DNE)
        #include <iostream> (DNE)
        #include <fstream> (DNE)
        #include <vector> (DNE)
        #include <numeric> (DNE)
        #include <algorithm> (DNE)
        #include <iomanip> (DNE)
        #include <cmath> (DNE)
      #include "options.h"
        #include <random> (DNE)
        #include <time.h> (DNE)
        #include <iostream> (DNE)
        #include "cuda_utils.h"
          #include "common.h"
            #include <cuda_runtime.h> (DNE)
            #include <thrust/host_vector.h> (DNE)
            #include <thrust/device_vector.h> (DNE)
            #include <thrust/generate.h> (DNE)
            #include <thrust/reduce.h> (DNE)
            #include <thrust/functional.h> (DNE)
            #include <thrust/random.h> (DNE)
            #include <thrust/sequence.h> (DNE)
            #include <thrust/transform.h> (DNE)
            #include <thrust/transform_reduce.h> (DNE)
            #include <thrust/iterator/counting_iterator.h> (DNE)
            #include <thrust/iterator/transform_iterator.h> (DNE)
            #include <thrust/iterator/permutation_iterator.h> (DNE)
            #include <thrust/iterator/constant_iterator.h> (DNE)
            #include <thrust/functional.h> (DNE)
            #include <thrust/fill.h> (DNE)
            #include <thrust/gather.h> (DNE)
            #include <thrust/sort.h> (DNE)
            #include <stdlib.h> (DNE)
            #include <stdio.h> (DNE)
            #include <assert.h> (DNE)
            #include <float.h> (DNE)
            #include <string.h> (DNE)
            #include <math.h> (DNE)
            #include <time.h> (DNE)
            #include <sys/time.h> (DNE)
            #include <random> (DNE)
            #include <stdexcept> (DNE)
            #include <iostream> (DNE)
            #include <fstream> (DNE)
            #include <vector> (DNE)
            #include <numeric> (DNE)
            #include <algorithm> (DNE)
            #include <iomanip> (DNE)
            #include <cmath> (DNE)
      #include "cuda_utils.h"
        #include "common.h"
          #include <cuda_runtime.h> (DNE)
          #include <thrust/host_vector.h> (DNE)
          #include <thrust/device_vector.h> (DNE)
          #include <thrust/generate.h> (DNE)
          #include <thrust/reduce.h> (DNE)
          #include <thrust/functional.h> (DNE)
          #include <thrust/random.h> (DNE)
          #include <thrust/sequence.h> (DNE)
          #include <thrust/transform.h> (DNE)
          #include <thrust/transform_reduce.h> (DNE)
          #include <thrust/iterator/counting_iterator.h> (DNE)
          #include <thrust/iterator/transform_iterator.h> (DNE)
          #include <thrust/iterator/permutation_iterator.h> (DNE)
          #include <thrust/iterator/constant_iterator.h> (DNE)
          #include <thrust/functional.h> (DNE)
          #include <thrust/fill.h> (DNE)
          #include <thrust/gather.h> (DNE)
          #include <thrust/sort.h> (DNE)
          #include <stdlib.h> (DNE)
          #include <stdio.h> (DNE)
          #include <assert.h> (DNE)
          #include <float.h> (DNE)
          #include <string.h> (DNE)
          #include <math.h> (DNE)
          #include <time.h> (DNE)
          #include <sys/time.h> (DNE)
          #include <random> (DNE)
          #include <stdexcept> (DNE)
          #include <iostream> (DNE)
          #include <fstream> (DNE)
          #include <vector> (DNE)
          #include <numeric> (DNE)
          #include <algorithm> (DNE)
          #include <iomanip> (DNE)
          #include <cmath> (DNE)
      #include "matrix_broadcast_utils.h"
        #include "common.h"
          #include <cuda_runtime.h> (DNE)
          #include <thrust/host_vector.h> (DNE)
          #include <thrust/device_vector.h> (DNE)
          #include <thrust/generate.h> (DNE)
          #include <thrust/reduce.h> (DNE)
          #include <thrust/functional.h> (DNE)
          #include <thrust/random.h> (DNE)
          #include <thrust/sequence.h> (DNE)
          #include <thrust/transform.h> (DNE)
          #include <thrust/transform_reduce.h> (DNE)
          #include <thrust/iterator/counting_iterator.h> (DNE)
          #include <thrust/iterator/transform_iterator.h> (DNE)
          #include <thrust/iterator/permutation_iterator.h> (DNE)
          #include <thrust/iterator/constant_iterator.h> (DNE)
          #include <thrust/functional.h> (DNE)
          #include <thrust/fill.h> (DNE)
          #include <thrust/gather.h> (DNE)
          #include <thrust/sort.h> (DNE)
          #include <stdlib.h> (DNE)
          #include <stdio.h> (DNE)
          #include <assert.h> (DNE)
          #include <float.h> (DNE)
          #include <string.h> (DNE)
          #include <math.h> (DNE)
          #include <time.h> (DNE)
          #include <sys/time.h> (DNE)
          #include <random> (DNE)
          #include <stdexcept> (DNE)
          #include <iostream> (DNE)
          #include <fstream> (DNE)
          #include <vector> (DNE)
          #include <numeric> (DNE)
          #include <algorithm> (DNE)
          #include <iomanip> (DNE)
          #include <cmath> (DNE)
        #include "cuda_utils.h"
          #include "common.h"
            #include <cuda_runtime.h> (DNE)
            #include <thrust/host_vector.h> (DNE)
            #include <thrust/device_vector.h> (DNE)
            #include <thrust/generate.h> (DNE)
            #include <thrust/reduce.h> (DNE)
            #include <thrust/functional.h> (DNE)
            #include <thrust/random.h> (DNE)
            #include <thrust/sequence.h> (DNE)
            #include <thrust/transform.h> (DNE)
            #include <thrust/transform_reduce.h> (DNE)
            #include <thrust/iterator/counting_iterator.h> (DNE)
            #include <thrust/iterator/transform_iterator.h> (DNE)
            #include <thrust/iterator/permutation_iterator.h> (DNE)
            #include <thrust/iterator/constant_iterator.h> (DNE)
            #include <thrust/functional.h> (DNE)
            #include <thrust/fill.h> (DNE)
            #include <thrust/gather.h> (DNE)
            #include <thrust/sort.h> (DNE)
            #include <stdlib.h> (DNE)
            #include <stdio.h> (DNE)
            #include <assert.h> (DNE)
            #include <float.h> (DNE)
            #include <string.h> (DNE)
            #include <math.h> (DNE)
            #include <time.h> (DNE)
            #include <sys/time.h> (DNE)
            #include <random> (DNE)
            #include <stdexcept> (DNE)
            #include <iostream> (DNE)
            #include <fstream> (DNE)
            #include <vector> (DNE)
            #include <numeric> (DNE)
            #include <algorithm> (DNE)
            #include <iomanip> (DNE)
            #include <cmath> (DNE)
      #include "thrust_transform_functions.h"
    #include "nbodyfft.h"
      #include <chrono> (DNE)
      #include <complex> (DNE)
      #include <thrust/complex.h> (DNE)
      #include "common.h"
        #include <cuda_runtime.h> (DNE)
        #include <thrust/host_vector.h> (DNE)
        #include <thrust/device_vector.h> (DNE)
        #include <thrust/generate.h> (DNE)
        #include <thrust/reduce.h> (DNE)
        #include <thrust/functional.h> (DNE)
        #include <thrust/random.h> (DNE)
        #include <thrust/sequence.h> (DNE)
        #include <thrust/transform.h> (DNE)
        #include <thrust/transform_reduce.h> (DNE)
        #include <thrust/iterator/counting_iterator.h> (DNE)
        #include <thrust/iterator/transform_iterator.h> (DNE)
        #include <thrust/iterator/permutation_iterator.h> (DNE)
        #include <thrust/iterator/constant_iterator.h> (DNE)
        #include <thrust/functional.h> (DNE)
        #include <thrust/fill.h> (DNE)
        #include <thrust/gather.h> (DNE)
        #include <thrust/sort.h> (DNE)
        #include <stdlib.h> (DNE)
        #include <stdio.h> (DNE)
        #include <assert.h> (DNE)
        #include <float.h> (DNE)
        #include <string.h> (DNE)
        #include <math.h> (DNE)
        #include <time.h> (DNE)
        #include <sys/time.h> (DNE)
        #include <random> (DNE)
        #include <stdexcept> (DNE)
        #include <iostream> (DNE)
        #include <fstream> (DNE)
        #include <vector> (DNE)
        #include <numeric> (DNE)
        #include <algorithm> (DNE)
        #include <iomanip> (DNE)
        #include <cmath> (DNE)
      #include "cuda_utils.h"
        #include "common.h"
          #include <cuda_runtime.h> (DNE)
          #include <thrust/host_vector.h> (DNE)
          #include <thrust/device_vector.h> (DNE)
          #include <thrust/generate.h> (DNE)
          #include <thrust/reduce.h> (DNE)
          #include <thrust/functional.h> (DNE)
          #include <thrust/random.h> (DNE)
          #include <thrust/sequence.h> (DNE)
          #include <thrust/transform.h> (DNE)
          #include <thrust/transform_reduce.h> (DNE)
          #include <thrust/iterator/counting_iterator.h> (DNE)
          #include <thrust/iterator/transform_iterator.h> (DNE)
          #include <thrust/iterator/permutation_iterator.h> (DNE)
          #include <thrust/iterator/constant_iterator.h> (DNE)
          #include <thrust/functional.h> (DNE)
          #include <thrust/fill.h> (DNE)
          #include <thrust/gather.h> (DNE)
          #include <thrust/sort.h> (DNE)
          #include <stdlib.h> (DNE)
          #include <stdio.h> (DNE)
          #include <assert.h> (DNE)
          #include <float.h> (DNE)
          #include <string.h> (DNE)
          #include <math.h> (DNE)
          #include <time.h> (DNE)
          #include <sys/time.h> (DNE)
          #include <random> (DNE)
          #include <stdexcept> (DNE)
          #include <iostream> (DNE)
          #include <fstream> (DNE)
          #include <vector> (DNE)
          #include <numeric> (DNE)
          #include <algorithm> (DNE)
          #include <iomanip> (DNE)
          #include <cmath> (DNE)
      #include "debug_utils.h"
        #include "common.h"
          #include <cuda_runtime.h> (DNE)
          #include <thrust/host_vector.h> (DNE)
          #include <thrust/device_vector.h> (DNE)
          #include <thrust/generate.h> (DNE)
          #include <thrust/reduce.h> (DNE)
          #include <thrust/functional.h> (DNE)
          #include <thrust/random.h> (DNE)
          #include <thrust/sequence.h> (DNE)
          #include <thrust/transform.h> (DNE)
          #include <thrust/transform_reduce.h> (DNE)
          #include <thrust/iterator/counting_iterator.h> (DNE)
          #include <thrust/iterator/transform_iterator.h> (DNE)
          #include <thrust/iterator/permutation_iterator.h> (DNE)
          #include <thrust/iterator/constant_iterator.h> (DNE)
          #include <thrust/functional.h> (DNE)
          #include <thrust/fill.h> (DNE)
          #include <thrust/gather.h> (DNE)
          #include <thrust/sort.h> (DNE)
          #include <stdlib.h> (DNE)
          #include <stdio.h> (DNE)
          #include <assert.h> (DNE)
          #include <float.h> (DNE)
          #include <string.h> (DNE)
          #include <math.h> (DNE)
          #include <time.h> (DNE)
          #include <sys/time.h> (DNE)
          #include <random> (DNE)
          #include <stdexcept> (DNE)
          #include <iostream> (DNE)
          #include <fstream> (DNE)
          #include <vector> (DNE)
          #include <numeric> (DNE)
          #include <algorithm> (DNE)
          #include <iomanip> (DNE)
          #include <cmath> (DNE)
      #include "matrix_broadcast_utils.h"
        #include "common.h"
          #include <cuda_runtime.h> (DNE)
          #include <thrust/host_vector.h> (DNE)
          #include <thrust/device_vector.h> (DNE)
          #include <thrust/generate.h> (DNE)
          #include <thrust/reduce.h> (DNE)
          #include <thrust/functional.h> (DNE)
          #include <thrust/random.h> (DNE)
          #include <thrust/sequence.h> (DNE)
          #include <thrust/transform.h> (DNE)
          #include <thrust/transform_reduce.h> (DNE)
          #include <thrust/iterator/counting_iterator.h> (DNE)
          #include <thrust/iterator/transform_iterator.h> (DNE)
          #include <thrust/iterator/permutation_iterator.h> (DNE)
          #include <thrust/iterator/constant_iterator.h> (DNE)
          #include <thrust/functional.h> (DNE)
          #include <thrust/fill.h> (DNE)
          #include <thrust/gather.h> (DNE)
          #include <thrust/sort.h> (DNE)
          #include <stdlib.h> (DNE)
          #include <stdio.h> (DNE)
          #include <assert.h> (DNE)
          #include <float.h> (DNE)
          #include <string.h> (DNE)
          #include <math.h> (DNE)
          #include <time.h> (DNE)
          #include <sys/time.h> (DNE)
          #include <random> (DNE)
          #include <stdexcept> (DNE)
          #include <iostream> (DNE)
          #include <fstream> (DNE)
          #include <vector> (DNE)
          #include <numeric> (DNE)
          #include <algorithm> (DNE)
          #include <iomanip> (DNE)
          #include <cmath> (DNE)
        #include "cuda_utils.h"
          #include "common.h"
            #include <cuda_runtime.h> (DNE)
            #include <thrust/host_vector.h> (DNE)
            #include <thrust/device_vector.h> (DNE)
            #include <thrust/generate.h> (DNE)
            #include <thrust/reduce.h> (DNE)
            #include <thrust/functional.h> (DNE)
            #include <thrust/random.h> (DNE)
            #include <thrust/sequence.h> (DNE)
            #include <thrust/transform.h> (DNE)
            #include <thrust/transform_reduce.h> (DNE)
            #include <thrust/iterator/counting_iterator.h> (DNE)
            #include <thrust/iterator/transform_iterator.h> (DNE)
            #include <thrust/iterator/permutation_iterator.h> (DNE)
            #include <thrust/iterator/constant_iterator.h> (DNE)
            #include <thrust/functional.h> (DNE)
            #include <thrust/fill.h> (DNE)
            #include <thrust/gather.h> (DNE)
            #include <thrust/sort.h> (DNE)
            #include <stdlib.h> (DNE)
            #include <stdio.h> (DNE)
            #include <assert.h> (DNE)
            #include <float.h> (DNE)
            #include <string.h> (DNE)
            #include <math.h> (DNE)
            #include <time.h> (DNE)
            #include <sys/time.h> (DNE)
            #include <random> (DNE)
            #include <stdexcept> (DNE)
            #include <iostream> (DNE)
            #include <fstream> (DNE)
            #include <vector> (DNE)
            #include <numeric> (DNE)
            #include <algorithm> (DNE)
            #include <iomanip> (DNE)
            #include <cmath> (DNE)
    #include "rep_forces.h"
      #include "common.h"
        #include <cuda_runtime.h> (DNE)
        #include <thrust/host_vector.h> (DNE)
        #include <thrust/device_vector.h> (DNE)
        #include <thrust/generate.h> (DNE)
        #include <thrust/reduce.h> (DNE)
        #include <thrust/functional.h> (DNE)
        #include <thrust/random.h> (DNE)
        #include <thrust/sequence.h> (DNE)
        #include <thrust/transform.h> (DNE)
        #include <thrust/transform_reduce.h> (DNE)
        #include <thrust/iterator/counting_iterator.h> (DNE)
        #include <thrust/iterator/transform_iterator.h> (DNE)
        #include <thrust/iterator/permutation_iterator.h> (DNE)
        #include <thrust/iterator/constant_iterator.h> (DNE)
        #include <thrust/functional.h> (DNE)
        #include <thrust/fill.h> (DNE)
        #include <thrust/gather.h> (DNE)
        #include <thrust/sort.h> (DNE)
        #include <stdlib.h> (DNE)
        #include <stdio.h> (DNE)
        #include <assert.h> (DNE)
        #include <float.h> (DNE)
        #include <string.h> (DNE)
        #include <math.h> (DNE)
        #include <time.h> (DNE)
        #include <sys/time.h> (DNE)
        #include <random> (DNE)
        #include <stdexcept> (DNE)
        #include <iostream> (DNE)
        #include <fstream> (DNE)
        #include <vector> (DNE)
        #include <numeric> (DNE)
        #include <algorithm> (DNE)
        #include <iomanip> (DNE)
        #include <cmath> (DNE)
      #include "options.h"
        #include <random> (DNE)
        #include <time.h> (DNE)
        #include <iostream> (DNE)
        #include "cuda_utils.h"
          #include "common.h"
            #include <cuda_runtime.h> (DNE)
            #include <thrust/host_vector.h> (DNE)
            #include <thrust/device_vector.h> (DNE)
            #include <thrust/generate.h> (DNE)
            #include <thrust/reduce.h> (DNE)
            #include <thrust/functional.h> (DNE)
            #include <thrust/random.h> (DNE)
            #include <thrust/sequence.h> (DNE)
            #include <thrust/transform.h> (DNE)
            #include <thrust/transform_reduce.h> (DNE)
            #include <thrust/iterator/counting_iterator.h> (DNE)
            #include <thrust/iterator/transform_iterator.h> (DNE)
            #include <thrust/iterator/permutation_iterator.h> (DNE)
            #include <thrust/iterator/constant_iterator.h> (DNE)
            #include <thrust/functional.h> (DNE)
            #include <thrust/fill.h> (DNE)
            #include <thrust/gather.h> (DNE)
            #include <thrust/sort.h> (DNE)
            #include <stdlib.h> (DNE)
            #include <stdio.h> (DNE)
            #include <assert.h> (DNE)
            #include <float.h> (DNE)
            #include <string.h> (DNE)
            #include <math.h> (DNE)
            #include <time.h> (DNE)
            #include <sys/time.h> (DNE)
            #include <random> (DNE)
            #include <stdexcept> (DNE)
            #include <iostream> (DNE)
            #include <fstream> (DNE)
            #include <vector> (DNE)
            #include <numeric> (DNE)
            #include <algorithm> (DNE)
            #include <iomanip> (DNE)
            #include <cmath> (DNE)
      #include "cuda_utils.h"
        #include "common.h"
          #include <cuda_runtime.h> (DNE)
          #include <thrust/host_vector.h> (DNE)
          #include <thrust/device_vector.h> (DNE)
          #include <thrust/generate.h> (DNE)
          #include <thrust/reduce.h> (DNE)
          #include <thrust/functional.h> (DNE)
          #include <thrust/random.h> (DNE)
          #include <thrust/sequence.h> (DNE)
          #include <thrust/transform.h> (DNE)
          #include <thrust/transform_reduce.h> (DNE)
          #include <thrust/iterator/counting_iterator.h> (DNE)
          #include <thrust/iterator/transform_iterator.h> (DNE)
          #include <thrust/iterator/permutation_iterator.h> (DNE)
          #include <thrust/iterator/constant_iterator.h> (DNE)
          #include <thrust/functional.h> (DNE)
          #include <thrust/fill.h> (DNE)
          #include <thrust/gather.h> (DNE)
          #include <thrust/sort.h> (DNE)
          #include <stdlib.h> (DNE)
          #include <stdio.h> (DNE)
          #include <assert.h> (DNE)
          #include <float.h> (DNE)
          #include <string.h> (DNE)
          #include <math.h> (DNE)
          #include <time.h> (DNE)
          #include <sys/time.h> (DNE)
          #include <random> (DNE)
          #include <stdexcept> (DNE)
          #include <iostream> (DNE)
          #include <fstream> (DNE)
          #include <vector> (DNE)
          #include <numeric> (DNE)
          #include <algorithm> (DNE)
          #include <iomanip> (DNE)
          #include <cmath> (DNE)
  #include "options.h"
    #include <random> (DNE)
    #include <time.h> (DNE)
    #include <iostream> (DNE)
    #include "cuda_utils.h"
      #include "common.h"
        #include <cuda_runtime.h> (DNE)
        #include <thrust/host_vector.h> (DNE)
        #include <thrust/device_vector.h> (DNE)
        #include <thrust/generate.h> (DNE)
        #include <thrust/reduce.h> (DNE)
        #include <thrust/functional.h> (DNE)
        #include <thrust/random.h> (DNE)
        #include <thrust/sequence.h> (DNE)
        #include <thrust/transform.h> (DNE)
        #include <thrust/transform_reduce.h> (DNE)
        #include <thrust/iterator/counting_iterator.h> (DNE)
        #include <thrust/iterator/transform_iterator.h> (DNE)
        #include <thrust/iterator/permutation_iterator.h> (DNE)
        #include <thrust/iterator/constant_iterator.h> (DNE)
        #include <thrust/functional.h> (DNE)
        #include <thrust/fill.h> (DNE)
        #include <thrust/gather.h> (DNE)
        #include <thrust/sort.h> (DNE)
        #include <stdlib.h> (DNE)
        #include <stdio.h> (DNE)
        #include <assert.h> (DNE)
        #include <float.h> (DNE)
        #include <string.h> (DNE)
        #include <math.h> (DNE)
        #include <time.h> (DNE)
        #include <sys/time.h> (DNE)
        #include <random> (DNE)
        #include <stdexcept> (DNE)
        #include <iostream> (DNE)
        #include <fstream> (DNE)
        #include <vector> (DNE)
        #include <numeric> (DNE)
        #include <algorithm> (DNE)
        #include <iomanip> (DNE)
        #include <cmath> (DNE)
  #include "cxxopts.hpp"
    #include <cctype> (DNE)
    #include <cstring> (DNE)
    #include <exception> (DNE)
    #include <iostream> (DNE)
    #include <limits> (DNE)
    #include <list> (DNE)
    #include <map> (DNE)
    #include <memory> (DNE)
    #include <sstream> (DNE)
    #include <string> (DNE)
    #include <unordered_map> (DNE)
    #include <unordered_set> (DNE)
    #include <utility> (DNE)
    #include <vector> (DNE)
    #include <algorithm> (DNE)
    #include <regex> (DNE)
    #include <optional> (DNE)
    #include <unicode/unistr.h> (DNE)

""",
}

EXPECTED_KERNELS = [
    {"file": "apply_forces.cu", "kernel": "IntegrationKernel", "line": 41},
    {"file": "attr_forces.cu", "kernel": "ComputePijxQijKernelV3", "line": 41},
    {"file": "attr_forces.cu", "kernel": "reduce_sum_kernel", "line": 71},
    {
        "file": "distance_utils.cu",
        "kernel": "PostprocessNeighborIndicesKernel",
        "line": 94,
    },
    {"file": "math_utils.cu", "kernel": "syv2k", "line": 62},
    {
        "file": "matrix_broadcast_utils.cu",
        "kernel": "BroadcastRowVector",
        "line": 46,
    },
    {
        "file": "matrix_broadcast_utils.cu",
        "kernel": "BroadcastColumnVector",
        "line": 65,
    },
    {"file": "nbodyfft.cu", "kernel": "copy_to_fft_input", "line": 50},
    {"file": "nbodyfft.cu", "kernel": "copy_from_fft_output", "line": 72},
    {"file": "nbodyfft.cu", "kernel": "compute_point_box_idx", "line": 94},
    {"file": "nbodyfft.cu", "kernel": "interpolate_device", "line": 128},
    {
        "file": "nbodyfft.cu",
        "kernel": "compute_interpolated_indices",
        "line": 159,
    },
    {"file": "nbodyfft.cu", "kernel": "compute_potential_indices", "line": 193},
    {"file": "nbodyfft.cu", "kernel": "compute_kernel_tilde", "line": 233},
    {
        "file": "nbodyfft.cu",
        "kernel": "compute_upper_and_lower_bounds",
        "line": 259,
    },
    {"file": "nbodyfft.cu", "kernel": "DFT2D1gpu", "line": 285},
    {"file": "nbodyfft.cu", "kernel": "DFT2D2gpu", "line": 307},
    {"file": "nbodyfft.cu", "kernel": "iDFT2D1gpu", "line": 331},
    {"file": "nbodyfft.cu", "kernel": "iDFT2D2gpu", "line": 359},
    {"file": "perplexity_search.cu", "kernel": "ComputePijKernel", "line": 40},
    {"file": "perplexity_search.cu", "kernel": "RowSumKernel", "line": 66},
    {"file": "perplexity_search.cu", "kernel": "NegEntropyKernel", "line": 86},
    {
        "file": "perplexity_search.cu",
        "kernel": "PerplexitySearchKernel",
        "line": 107,
    },
    {
        "file": "rep_forces.cu",
        "kernel": "compute_repulsive_forces_kernel",
        "line": 33,
    },
    {
        "file": "rep_forces.cu",
        "kernel": "compute_chargesQij_kernel",
        "line": 90,
    },
]


